#!/usr/bin/env python3
"""
proto-sync.py — Auto-generate UI prototypes from OpenAPI spec.

Factory canonical generator: factory/ui-sync-core/proto-sync.py
Drift-checked by: factory-watchdog Mode 3 check #6

Triggered automatically via:
  - PostToolUse hook when api/routers/* or api/models/* change
  - post-task.sh when API-related files are in the last commit
  - Manually: python3 proto-sync.py [--dry-run]

Strategy:
  1. Try live API at OPENAPI_URL
  2. Fallback: import FastAPI app directly (no server needed)
  3. Fallback: use saved snapshot apps/.openapi-snapshot.json

Environment variables:
  OPENAPI_URL          — live API endpoint (default: http://localhost:8090/openapi.json)
  WEB_COMPONENTS_DIR   — web generated output (default: apps/web/components/generated)
  MOBILE_COMPONENTS_DIR — mobile generated output (default: apps/mobile/components/generated)
  SNAPSHOT_PATH        — OpenAPI snapshot location (default: apps/.openapi-snapshot.json)
  STORYBOOK_TITLE_PREFIX — Storybook story title prefix (default: Generated)
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import sys
import urllib.error
import urllib.request

ROOT = Path(__file__).parent.parent if not os.getenv("PROTO_SYNC_ROOT") else Path(os.environ["PROTO_SYNC_ROOT"])
OPENAPI_URL = os.getenv("OPENAPI_URL", "http://localhost:8090/openapi.json")
PROTO_WEB = Path(os.getenv("WEB_COMPONENTS_DIR", str(ROOT / "apps/web/components/generated")))
PROTO_MOBILE = Path(os.getenv("MOBILE_COMPONENTS_DIR", str(ROOT / "apps/mobile/components/generated")))
SNAPSHOT_PATH = Path(os.getenv("SNAPSHOT_PATH", str(ROOT / "apps/.openapi-snapshot.json")))
STORYBOOK_PREFIX = os.getenv("STORYBOOK_TITLE_PREFIX", "Generated")

# Routes that are infrastructure — skip prototype generation
SKIP_PREFIXES = {"/health", "/metrics", "/docs", "/openapi.json", "/redoc"}


# ── Spec acquisition ──────────────────────────────────────────────────────────


def _fetch_live(url: str) -> dict | None:
    try:
        with urllib.request.urlopen(url, timeout=3) as r:  # nosec B310 — localhost only
            return json.loads(r.read())
    except Exception:
        return None


def _extract_from_app() -> dict | None:
    """Import FastAPI app and call app.openapi() — no server required."""
    try:
        sys.path.insert(0, str(ROOT))
        from api.main import app  # type: ignore[import]

        return app.openapi()
    except Exception as exc:
        print(f"  app-import: {exc}")
        return None


def get_openapi_spec() -> dict | None:
    # 1. Live server
    spec = _fetch_live(OPENAPI_URL)
    if spec:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(json.dumps(spec, indent=2))
        return spec

    # 2. Direct FastAPI import (offline)
    print("INFO: API offline, trying direct import...")
    spec = _extract_from_app()
    if spec:
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(json.dumps(spec, indent=2))
        return spec

    # 3. Saved snapshot
    if SNAPSHOT_PATH.exists():
        print("INFO: using saved snapshot")
        return json.loads(SNAPSHOT_PATH.read_text())

    return None


# ── Naming ────────────────────────────────────────────────────────────────────


def route_to_component_name(path: str, method: str) -> str:
    """Convert /v1/payments/{id} GET → PaymentsDetailView"""
    parts = [
        p for p in path.split("/") if p and not p.startswith("{") and p not in ("v1", "v2", "api")
    ]
    name = "".join(p.replace("-", "_").replace("_", " ").title().replace(" ", "") for p in parts)
    suffix = {
        "get": "View",
        "post": "Form",
        "put": "EditForm",
        "patch": "EditForm",
        "delete": "DeleteConfirm",
    }
    return name + suffix.get(method, "View")


# ── Web component ─────────────────────────────────────────────────────────────


def generate_web_component(name: str, route_info: dict, path: str, method: str) -> str:
    summary = route_info.get("summary", name)
    tags = route_info.get("tags", ["General"])
    has_body = "requestBody" in route_info
    form_open = (
        "<form onSubmit={(e) => { e.preventDefault(); onSuccess?.(); }}>" if has_body else "<div>"
    )
    form_close = "</form>" if has_body else "</div>"

    return f"""\
/**
 * AUTO-GENERATED by proto-sync.py — DO NOT EDIT MANUALLY
 * Source: {method.upper()} {path}
 * Tags: {", ".join(tags)}
 */
import "../../tokens/tokens.css";

interface {name}Props {{
  onSuccess?: () => void;
  onError?: (error: Error) => void;
}}

export function {name}({{ onSuccess, onError }}: {name}Props): React.ReactElement {{
  return (
    <section data-financial aria-label="{summary}">
      <header style={{{{ marginBottom: "var(--spacing-4)" }}}}>
        <h2 style={{{{ color: "var(--color-text-primary)", margin: 0 }}}}>{summary}</h2>
        <small data-disclosure style={{{{ color: "var(--color-text-muted)" }}}}>
          Auto-generated prototype · {", ".join(tags)}
        </small>
      </header>
      {form_open}
        {{/* Proto stub — replace with real implementation */}}
        <p style={{{{ fontFamily: "monospace", fontSize: 12 }}}}>
          {method.upper()} {path}
        </p>
      {form_close}
    </section>
  );
}}

export default {name};
"""


# ── Mobile component ──────────────────────────────────────────────────────────


def generate_mobile_component(name: str, route_info: dict, path: str, method: str) -> str:
    summary = route_info.get("summary", name)
    has_body = "requestBody" in route_info
    extra_imports = ", ScrollView, TouchableOpacity" if has_body else ""

    return f"""\
/**
 * AUTO-GENERATED by proto-sync.py — DO NOT EDIT MANUALLY
 * Source: {method.upper()} {path}
 */
import {{ View, Text, StyleSheet{extra_imports} }} from "react-native";
import {{ TOKENS }} from "../../../tokens";

interface {name}Props {{
  onSuccess?: () => void;
  onError?: (error: Error) => void;
}}

export function {name}({{ onSuccess, onError }}: {name}Props): React.ReactElement {{
  return (
    <View
      style={{styles.container}}
      accessible
      accessibilityRole="none"
      accessibilityLabel="{summary}"
    >
      <Text style={{styles.title}}>{summary}</Text>
      <Text style={{styles.route}}>{method.upper()} {path}</Text>
      <View style={{styles.disclosure}}>
        <Text style={{styles.disclosureText}}>Auto-generated prototype</Text>
      </View>
    </View>
  );
}}

const styles = StyleSheet.create({{
  container: {{
    backgroundColor: TOKENS.bgCard,
    borderWidth: 1,
    borderColor: TOKENS.borderDefault,
    borderRadius: TOKENS.radiusXl,
    padding: TOKENS.spacing6,
    gap: TOKENS.spacing3,
  }},
  title: {{
    fontSize: 16,
    fontWeight: "600",
    color: TOKENS.textSecondary,
  }},
  route: {{
    fontSize: 11,
    fontVariant: ["tabular-nums"],
    color: TOKENS.textMuted,
    fontFamily: "monospace",
  }},
  disclosure: {{
    borderTopWidth: 1,
    borderTopColor: TOKENS.borderDefault,
    paddingTop: TOKENS.spacing3,
    marginTop: TOKENS.spacing1,
  }},
  disclosureText: {{
    fontSize: 11,
    color: TOKENS.textMuted,
  }},
}});

export default {name};
"""


# ── Storybook story ───────────────────────────────────────────────────────────


def generate_story(name: str) -> str:
    return f"""\
/**
 * AUTO-GENERATED by proto-sync.py
 */
import type {{ Meta, StoryObj }} from "@storybook/react";
import {{ {name} }} from "./{name}";

const meta = {{
  title: "{STORYBOOK_PREFIX}/{name}",
  component: {name},
  tags: ["autodocs", "auto-generated"],
}} satisfies Meta<typeof {name}>;

export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {{}};
"""


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    dry_run = "--dry-run" in sys.argv

    spec = get_openapi_spec()
    if not spec:
        print("SKIP: no OpenAPI spec available (API offline, no snapshot)")
        sys.exit(0)

    paths = spec.get("paths", {})

    if not dry_run:
        PROTO_WEB.mkdir(parents=True, exist_ok=True)
        PROTO_MOBILE.mkdir(parents=True, exist_ok=True)

    generated: list[str] = []
    skipped: list[str] = []

    for path, methods in paths.items():
        if any(path.startswith(s) for s in SKIP_PREFIXES):
            continue

        for method, route_info in methods.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue

            name = route_to_component_name(path, method)

            web_dir = PROTO_WEB / name
            web_file = web_dir / f"{name}.tsx"
            web_story = web_dir / f"{name}.stories.tsx"

            mob_dir = PROTO_MOBILE / name
            mob_file = mob_dir / f"{name}.tsx"
            mob_story = mob_dir / f"{name}.stories.tsx"

            if not web_file.exists():
                if not dry_run:
                    web_dir.mkdir(parents=True, exist_ok=True)
                    web_file.write_text(generate_web_component(name, route_info, path, method))
                    web_story.write_text(generate_story(name))
                generated.append(f"WEB   {name}")
            else:
                skipped.append(name)

            if not mob_file.exists():
                if not dry_run:
                    mob_dir.mkdir(parents=True, exist_ok=True)
                    mob_file.write_text(generate_mobile_component(name, route_info, path, method))
                    mob_story.write_text(generate_story(name))
                generated.append(f"MOB   {name}")

    n_web = sum(1 for g in generated if g.startswith("WEB"))
    n_mob = sum(1 for g in generated if g.startswith("MOB"))

    mode = "[DRY-RUN] " if dry_run else ""
    if generated:
        print(f"{mode}proto-sync: +{n_web} web, +{n_mob} mobile ({len(skipped)} existing preserved)")
        for g in generated[:10]:
            print(f"  {g}")
        if len(generated) > 10:
            print(f"  ... and {len(generated) - 10} more")
    else:
        web_count = len(list(PROTO_WEB.glob("*/*.tsx"))) if PROTO_WEB.exists() else 0
        mob_count = len(list(PROTO_MOBILE.glob("*/*.tsx"))) if PROTO_MOBILE.exists() else 0
        print(f"{mode}proto-sync: up-to-date ({web_count} web, {mob_count} mobile)")


if __name__ == "__main__":
    main()
