#!/usr/bin/env bash
# rollout-canon-to-repo.sh — Factory Canon rollout (C4, template)
#
# Pins the Factory canon (controlled copies) into a downstream bank repository
# at a specific Factory version. Creates a branch + PR; never force-pushes.
#
# Usage:
#   ./rollout-canon-to-repo.sh <target-repo-slug> [--version vX.Y.Z] [--dry-run]
#
# Example:
#   ./rollout-canon-to-repo.sh CarmiBanxe/banxe-payment-core --version v1.5.1 --dry-run
#
# Requirements: gh (authenticated), git, rsync. Target repo must exist and the
# caller must have push access (Sprint 6 prerequisite — RED-OPEN #1).

set -euo pipefail

# ---- args -------------------------------------------------------------------
TARGET="${1:-}"
VERSION=""
DRY_RUN=0
shift || true
while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$TARGET" ]; then
  echo "ERROR: target repo slug required (e.g. CarmiBanxe/banxe-payment-core)" >&2
  exit 2
fi

# ---- resolve factory version ------------------------------------------------
FACTORY_ROOT="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
cd "$FACTORY_ROOT"
if [ -z "$VERSION" ]; then
  VERSION="$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")"
fi
echo "== Factory rollout =="
echo "Factory root : $FACTORY_ROOT"
echo "Factory ver  : $VERSION"
echo "Target repo  : $TARGET"
echo "Dry run      : $DRY_RUN"

# ---- controlled copies to distribute ----------------------------------------
CONTROLLED_FILES=(
  "CANON.md"
  ".clauderules"
  ".github/workflows/canon-guardian.yml"
  ".github/workflows/canon-guardian-regression.yml"
  ".claude/agents/canon-guardian.md"
  "docs/canon/CANON-TOPOLOGY.md"
  "docs/canon/OVERRIDES.md"
  "docs/canon/MODULES.md"
)

# ---- verify all controlled files exist locally ------------------------------
for f in "${CONTROLLED_FILES[@]}"; do
  [ -f "$f" ] || { echo "ERROR: controlled file missing in factory: $f" >&2; exit 1; }
done

# ---- prepare workspace ------------------------------------------------------
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
BRANCH="canon-pin/$VERSION"

echo "== Cloning target =="
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] gh repo clone $TARGET $WORK/repo"
else
  gh repo clone "$TARGET" "$WORK/repo" -- --depth 1
fi

# ---- copy controlled files --------------------------------------------------
echo "== Copying controlled copies =="
for f in "${CONTROLLED_FILES[@]}"; do
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[dry-run] copy $f -> $TARGET/$f"
  else
    mkdir -p "$WORK/repo/$(dirname "$f")"
    cp "$FACTORY_ROOT/$f" "$WORK/repo/$f"
  fi
done

# ---- write version pin ------------------------------------------------------
PIN_FILE=".factory-canon-version"
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] write $PIN_FILE = $VERSION"
else
  echo "$VERSION" > "$WORK/repo/$PIN_FILE"
fi

# ---- commit + PR ------------------------------------------------------------
if [ "$DRY_RUN" -eq 1 ]; then
  echo "[dry-run] git checkout -b $BRANCH"
  echo "[dry-run] git add + commit 'chore(canon): pin Factory $VERSION'"
  echo "[dry-run] git push origin $BRANCH"
  echo "[dry-run] gh pr create --base main --title 'Pin Factory canon $VERSION'"
  echo "== Dry run complete. No changes made to $TARGET. =="
  exit 0
fi

cd "$WORK/repo"
git checkout -b "$BRANCH"
git add "${CONTROLLED_FILES[@]}" "$PIN_FILE"
git commit -m "chore(canon): pin Factory canon $VERSION

Distributes Factory controlled copies (CANON.md, .clauderules,
canon-guardian workflows, agents, canon docs) pinned at Factory $VERSION.
Generated by factory/scripts/rollout-canon-to-repo.sh."
git push -u origin "$BRANCH"
gh pr create \
  --base main \
  --head "$BRANCH" \
  --title "chore(canon): pin Factory canon $VERSION" \
  --body "Automated canon rollout from factory $VERSION. Review controlled-copy diffs before merge. Branch protection + canon-guardian must pass."

echo "== Rollout PR created for $TARGET at $VERSION =="
